version: '3'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: erp
    ports:
      - 3307:3306
    networks:
      - springdata

  app:
    image: erp
    restart: always
    environment:
      - SERVER_PORT=8080
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/erp
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
    ports:
      - 9090:8080
      - 587:587
    depends_on:
      - db
    networks:
      - springdata
networks:
  springdata:

